server:
  port: 9999
  servlet.context-path: /
  
  
  #Local DB
spring.datasource:  
  url: jdbc:mysql://localhost:3306/filesave?serverTimezone=UTC&autoReconnect=true
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: piyush  
  
  
spring.jpa:
  database-platform: org.hibernate.dialect.MySQL5Dialect
  properties:
    hibernate.show_sql: true
    hibernate.format_sql: true  